USE usto;
INSERT INTO TB_G2B001D (
    G2B_D_CD,
    G2B_M_CD,
    G2B_D_NM,
    G2B_UPR,
    CRE_BY,
    CRE_AT
)
SELECT
    G2B_D_CD,
    ANY_VALUE(G2B_M_CD),
    ANY_VALUE(G2B_D_NM),
    MAX(G2B_UPR),
    'SYSTEM',
    NOW()
FROM TB_G2B_RAW
WHERE G2B_D_CD IS NOT NULL
  AND G2B_M_CD IS NOT NULL
  AND G2B_UPR IS NOT NULL
GROUP BY G2B_D_CD; -- 매우 오래걸립니다.(렉 아니에요)

SELECT COUNT(*) AS row_count FROM TB_G2B001D;
SELECT * FROM TB_G2B001D LIMIT 100;