USE usto;

INSERT INTO TB_G2B001M (
    G2B_M_CD,
    G2B_M_NM,
    CRE_BY,
    CRE_AT
)
SELECT DISTINCT
    G2B_M_CD,
    G2B_M_NM,
    'SYSTEM',
    NOW()
FROM TB_G2B_RAW
WHERE G2B_M_CD IS NOT NULL;

SELECT COUNT(*) AS row_count FROM TB_G2B001M;
SELECT * FROM TB_G2B001M LIMIT 100;
