
spring.test.username=dev-user

spring.datasource.url=jdbc:mysql://localhost:3306/dev_db?serverTimezone=Asia/Seoul&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=${DB_DEV_PW}

spring.flyway.default-schema=dev_db
spring.flyway.placeholders.schema=dev_db