
spring.test.username=prod-user

spring.datasource.url=jdbc:mysql://${RDS_ENDPOINT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=utf8
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.default-schema=usto
spring.flyway.placeholders.schema=usto