#way to do release properties:  RUN->Edit Configurations->Active profiles = release

spring.test.username=prod-user

#database(mysql) should be same this environment variables
spring.datasource.url=jdbc:mysql://${RDS_ENDPOINT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=utf8
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}