/*
 [V-n 작업 일괄 취소]
 싱크가 안 맞는 문제가 발생한다면
 추후 없애야하는 파일입니다. 굉장히 위험하기 때문에 초기 작업 완료하면 삭제할겁니다.
 */
 USE usto;
 SET FOREIGN_KEY_CHECKS = 0; -- 외래 키 검사 끄기
 DROP TABLE IF EXISTS flyway_schema_history; -- Flyway 실패기록 삭제
 DROP TABLE IF EXISTS TB_USER001M;
 DROP TABLE IF EXISTS TB_ORG002M;
 DROP TABLE IF EXISTS TB_ORG001M;
 DROP TABLE IF EXISTS TB_VERIF001M;
-- G2B
 DROP TABLE IF EXISTS TB_G2B_RAW;
 DROP TABLE IF EXISTS TB_G2B001D;
 DROP TABLE IF EXISTS TB_G2B001M;
-- ITEM
 DROP TABLE IF EXISTS
    TB_ITEM001M,
    TB_ITEM002M, TB_ITEM002D,
    TB_ITEM003M, TB_ITEM003D,
    TB_ITEM004M, TB_ITEM004D,
    TB_ITEM005M, TB_ITEM005D,
    TB_ITEM006M;
 DROP DATABASE usto;
 CREATE DATABASE usto;
 USE usto;
 DROP TABLE IF EXISTS flyway_schema_history;
 SET FOREIGN_KEY_CHECKS = 1;
