### 1. 이메일 인증번호 발송
POST http://localhost:8080/api/auth/verification/email/send
Content-Type: application/json

{
  "usrId": "",
  "usrNm": "",
  "emailId": "badbergjr"
}

### 2. 이메일 인증번호 확인
POST http://localhost:8080/api/auth/verification/email/check
Content-Type: application/json

{
  "code": "220788"
}

### 3. SMS 인증번호 발송
POST http://localhost:8080/api/auth/verification/sms/send
Content-Type:  application/json

{
  "target": "01099569414"
}

### 4. SMS 인증번호 확인
POST http://localhost:8080/api/auth/verification/sms/check
Content-Type:  application/json

{
  "code": "082138"
}

### 5. 회원가입 -- 삭제 회원 관리에 대한 고민
POST http://localhost:8080/api/users/sign-up
Content-Type: application/json

{
  "usrId": "badbergjr",
  "usrNm": "박도현",
  "pwd": "1111",
  "orgCd": "HANYANG_ERICA"
}

### 6. 로그인 //홈화면 고려해서 좀 더 보강 예정 //승인되지 않은 사용자라는걸 알려주자//삭제된 사용라는 것도 (적용이 안됌)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "usrId": "badbergjr",
  "pwd": "1111"
}


### 7. 회원 정보 수정 (로그인 필요) - 전화번호는 인증을 해야 변경할 수 있어야한다
PUT http://localhost:8080/api/users/update
Content-Type: application/json

{
  "newUsrNm": "박도현",
  "newSms": "01099569414",
  "newPw": "1111"
}

### 8. 아이디 중복 확인 - 별도인지 확인해야한다.
GET http://localhost:8080/api/users/exists/user-id
Content-Type: application/json

{
  "usrId" : "badbergjr"
}

### 9. 이메일 중복 확인
GET http://localhost:8080/api/users/exists/email
Content-Type: application/json

{
  "emailId" : "badbergjr"
}

### 전화번호 중복 확인
GET http://localhost:8080/api/users/exists/sms
Content-Type: application/json

{
  "sms" : "01099569414"
}

### 10. 아이디 찾기
POST http://localhost:8080/api/auth/find/user-id

### 12. 비밀번호 재설정 //토큰 명 정상화
POST http://localhost:8080/api/auth/find/password
Content-Type: application/json

{
  "pwd": "1111",
  "pwdConfirm" : "1111"

}

### 13. 로그아웃
POST http://localhost:8080/api/auth/logout

### 14. 회원탈퇴
DELETE http://localhost:8080/api/users/delete
Content-Type: application/json

{
  "currentPw": "1111"
}


