use usto;

-- TB_ORG001M
CREATE TABLE `TB_ORG001M` (
  `ORG_CD` CHAR(7)  NOT NULL COMMENT '조직코드(의미코드)',
  `ORG_NM` VARCHAR(100)  NOT NULL COMMENT '조직명',
    --
  `CRE_BY` VARCHAR(100)   NOT NULL COMMENT '생성자ID',
  `CRE_AT` DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `UPD_BY` VARCHAR(100)   NULL COMMENT '수정자ID',
  `UPD_AT` DATETIME      NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
  PRIMARY KEY (`ORG_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TB_ORG002M
CREATE TABLE `TB_ORG002M` (
  `DEPT_CD` CHAR(5)      NOT NULL COMMENT '운용부서코드(의미코드, 조직 내 유일)',
  `ORG_CD`  CHAR(7)      NOT NULL COMMENT '조직코드(FK)',
  `DEPT_NM` VARCHAR(255)  NOT NULL COMMENT '운용부서명',
  `UP_DEPT_NM`  VARCHAR(255) NULL COMMENT '상위부서명',
  `CRE_BY`  VARCHAR(100)   NOT NULL COMMENT '생성자',
  `CRE_AT`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `UPD_BY`  VARCHAR(100)   NULL COMMENT '수정자',
  `UPD_AT`  DATETIME      NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',
  PRIMARY KEY (`ORG_CD`, `DEPT_CD`), 
  CONSTRAINT `FK_TB_ORG002M_ORG`
    FOREIGN KEY (`ORG_CD`) REFERENCES `TB_ORG001M` (`ORG_CD`)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,
  KEY `IX_TB_ORG002M_DEPT_CD` (`DEPT_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
