use usto;

-- TB_USER001M
CREATE TABLE `TB_USER001M` (
  `USR_ID`  VARCHAR(50)   NOT NULL COMMENT '사용자ID(로그인ID, 회원가입 시 사용자가 설정)',
  `USR_NM`  VARCHAR(50)   NOT NULL COMMENT '사용자명',
  `PW_HASH` VARCHAR(255)  NOT NULL COMMENT '비밀번호(해시)',
  `EMAIL`   VARCHAR(50)   NOT NULL COMMENT '이메일(UNIQUE)',
  `SMS`  CHAR(11)      NOT NULL COMMENT '전화번호',
  `ROLE_ID` VARCHAR(20)   NOT NULL DEFAULT 'GUEST' COMMENT '역할ID(ADMIN,MANAGER,GUEST)',
  `APPR_STS` VARCHAR(20) NOT NULL DEFAULT 'WAIT' COMMENT '승인여부(APPROVED,WAIT,REJECTED,SUSPENDED)',
  `APPR_USR_ID` VARCHAR(50) NULL COMMENT '승인자ID',
  `APPR_AT` DATETIME NULL COMMENT '승인일자',
  `ORG_CD`  VARCHAR(50)      NOT NULL COMMENT '조직코드(FK)',
    --
  `CRE_BY`  VARCHAR(100)   NOT NULL COMMENT '생성자ID',
  `CRE_AT`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `UPD_BY`  VARCHAR(100 )   NULL COMMENT '수정자ID',
  `UPD_AT`  DATETIME      NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',

  PRIMARY KEY (`USR_ID`),

  UNIQUE KEY `UK_TB_USER001M_EMAIL` (`EMAIL`),

  UNIQUE KEY `UK_TB_USER001M_SMS` (`SMS`),

  CONSTRAINT CK_TB_USER001M_ROLE_ID
      CHECK (ROLE_ID IN ('ADMIN','MANAGER','GUEST')),

  CONSTRAINT CK_TB_USER001M_APPR_STS
      CHECK (APPR_STS IN ('APPROVED','WAIT','REJECTED','SUSPENDED')),

  CONSTRAINT `FK_TB_USER001M_ORG`
    FOREIGN KEY (`ORG_CD`) REFERENCES `TB_ORG001M` (`ORG_CD`)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
