USE usto;

CREATE TABLE TB_VERIF001M (
  VERIF_ID     BIGINT       NOT NULL AUTO_INCREMENT COMMENT '인증ID',
  VERIF_PURPOSE VARCHAR(30) NOT NULL COMMENT '목적(SIGNUP,FIND_ID,RESET_PASSWORD)',
  VERIF_TYPE   VARCHAR(20)  NOT NULL COMMENT '타입(EMAIL/SMS)',
  TARGET       VARCHAR(255) NOT NULL COMMENT '인증대상(이메일/전화번호)',
  VERIF_CODE   VARCHAR(20)  NOT NULL COMMENT '인증코드(1234,123456)',
  EXPIRES_AT   DATETIME     NOT NULL COMMENT '만료시각',
  IS_VERIFIED  CHAR(1)      NOT NULL DEFAULT 'N' COMMENT '인증성공여부(Y/N)',
  VERIFIED_AT  DATETIME     NULL COMMENT '인증성공시각',
    --
  `CRE_BY` VARCHAR(100)   NOT NULL COMMENT '생성자ID',
  `CRE_AT` DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `UPD_BY` VARCHAR(100)   NULL COMMENT '수정자ID',
  `UPD_AT` DATETIME      NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',

  PRIMARY KEY (VERIF_ID),

  CONSTRAINT CK_TB_VERIF001M_TYPE
    CHECK (VERIF_TYPE IN ('EMAIL','SMS')),

  CONSTRAINT CK_TB_VERIF001M_YN
    CHECK (IS_VERIFIED IN ('Y','N')),

  CONSTRAINT CK_TB_VERIF001M_PURPOSE
      CHECK (VERIF_PURPOSE IN ('SIGNUP','FIND_ID','RESET_PASSWORD')),

  CONSTRAINT UK_TB_VERIF001M_TYPE_PURPOSE_TARGET
      UNIQUE (VERIF_TYPE, VERIF_PURPOSE, TARGET),

  KEY IX_TB_VERIF001M_LOOKUP (VERIF_TYPE, VERIF_PURPOSE, TARGET),

  KEY IX_TB_VERIF001M_EXPIRES (EXPIRES_AT)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
