USE usto;
/*
    해야할 것
    1. PURPOSE 컬럼 추가
    2. enum 타입들 check 조건 추가
    3. VERIF_TYPE, PURPOSE, TARGET는 유니크 제약 조건 추가 + 흠..
    4. org_cd 칼럼 삭제 (로직에서 문제가 생김.. 회원 가입 당시에는 이게 없음)


    + 예영님과 상의 후에 마이그레이션을 다시 짤거긴한데, 일단 메모용으로라도 남깁니다.


-- 1) PURPOSE 컬럼 추가
ALTER TABLE TB_VERIF001M
    ADD COLUMN VERIF_PURPOSE VARCHAR(20) NOT NULL COMMENT '목적(SIGNUP/FIND_ID/RESET_PASSWORD)'
        AFTER TARGET;

-- 2-1) PURPOSE 체크 제약
ALTER TABLE TB_VERIF001M
    ADD CONSTRAINT CK_TB_VERIF001M_VERIF_PURPOSE
        CHECK (VERIF_PURPOSE IN ('SIGNUP','FIND_ID','RESET_PASSWORD'));

-- 2-1) VERIF_TYPE 체크 제약
ALTER TABLE TB_VERIF001M
    ADD CONSTRAINT CK_TB_VERIF001M_VERIF_TYPE
        CHECK (VERIF_TYPE IN ('EMAIL','PHONE'));

-- 2-3)ROLE_ID 체크 제약
ALTER TABLE TB_USER001M
    ADD CONSTRAINT CK_TB_USER001M_ROLE_ID
        CHECK (ROLE_ID IN ('ADMIN','MANAGER','GUEST'));

-- 2-4)APPR_STS 체크 제약
ALTER TABLE TB_USER001M
    ADD CONSTRAINT CK_TB_USER001M_APPR_STS
        CHECK (APPR_STS IN ('APPROVED','WAIT','REJECTED','SUSPENDED'));


-- 3-1) 기존 유니크/인덱스 제거
ALTER TABLE TB_VERIF001M
    DROP INDEX UK_TB_VERIF001M_TARGET;

ALTER TABLE TB_VERIF001M
    DROP INDEX IX_TB_VERIF001M_LOOKUP;

-- 3-2) 신규 유니크/인덱스 추가 (핵심)
ALTER TABLE TB_VERIF001M
    ADD CONSTRAINT UK_TB_VERIF001M_TYPE_PURPOSE_TARGET
        UNIQUE (VERIF_TYPE, VERIF_PURPOSE, TARGET),
    ADD INDEX IX_TB_VERIF001M_LOOKUP (VERIF_TYPE, VERIF_PURPOSE, TARGET);

-- 4) 칼럼 삭제
ALTER TABLE TB_VERIF001M
    DROP COLUMN ORG_CD;

 */
