use usto;

-- TB_G2B_RAW
CREATE TABLE TB_G2B_RAW (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `G2B_M_CD` char(8),
  `G2B_M_NM` varchar(300),
  `G2B_D_CD` char(8),
  `G2B_D_NM` varchar(300),
  `G2B_UPR` DECIMAL(20,0),
  `G2B_UPR_RAW` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TB_G2B001M
CREATE TABLE TB_G2B001M (
  `G2B_M_CD` CHAR(8) PRIMARY KEY COMMENT '물품분류코드',
  `G2B_M_NM` VARCHAR(300) NOT NULL COMMENT '물품분류명',
    --
  `CRE_BY` VARCHAR(100)   NOT NULL COMMENT '생성자ID',
  `CRE_AT` DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `UPD_BY` VARCHAR(100)   NULL COMMENT '수정자ID',
  `UPD_AT` DATETIME      NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TB_G2B001D
CREATE TABLE TB_G2B001D (
  `G2B_D_CD` CHAR(8)  PRIMARY KEY COMMENT '물품식별코드',
  `G2B_M_CD` CHAR(8) NOT NULL COMMENT '물품분류코드 FK TB_G2B001M',
  `G2B_D_NM` VARCHAR(300) NOT NULL COMMENT '물품품목명',
  `G2B_UPR` DECIMAL(20,0) NOT NULL COMMENT '조달청 기준 계약단가(원)',
    --
  `CRE_BY` VARCHAR(100)   NOT NULL COMMENT '생성자ID',
  `CRE_AT` DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `UPD_BY` VARCHAR(100)   NULL COMMENT '수정자ID',
  `UPD_AT` DATETIME      NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자',

  KEY IDX_TB_G2B001D_M (G2B_M_CD),

  CONSTRAINT FK_TB_G2B001D_M
    FOREIGN KEY (G2B_M_CD)
    REFERENCES TB_G2B001M (G2B_M_CD)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_RAW_DCD_UPR ON TB_G2B_RAW (G2B_D_CD, G2B_UPR); -- 오래 걸림

CREATE TABLE TB_G2B_STG
(
    `STG_ID`   BIGINT AUTO_INCREMENT PRIMARY KEY,
    `G2B_M_CD` CHAR(8) NOT NULL COMMENT '물품분류코드',
    `G2B_M_NM` VARCHAR(300) NOT NULL COMMENT '물품분류명',
    `G2B_D_CD` CHAR(8) NOT NULL COMMENT '물품식별코드',
    `G2B_D_NM` VARCHAR(300) NOT NULL COMMENT '물품품목명',
    `G2B_UPR`  DECIMAL(20, 0) NOT NULL COMMENT '조달청 기준 계약단가(원)'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;