-- TB_ITEM002M(물품대장기본) 테이블에 취득정리구분 컬럼 추가
ALTER TABLE `TB_ITEM002M`
    ADD COLUMN `ACQ_ARRG_TY` VARCHAR(20) NOT NULL COMMENT '취득정리구분' AFTER `ARRG_AT`; -- 스냅샷


-- TB_ITEM002D(물품대장상세) 테이블에 기존 PK 삭제 후 복합키(물품번호 + 조직코드)로 재설정
ALTER TABLE `TB_ITEM002D` DROP PRIMARY KEY;
ALTER TABLE `TB_ITEM002D` ADD PRIMARY KEY (`ITM_NO`, `ORG_CD`);