-- 1) 기존 CHG_CNT를 SyncResult 의미에 맞게 CHANGED로 rename
ALTER TABLE TB_G2B_SYNC_HIS
    CHANGE COLUMN CHG_CNT CHANGED BIGINT NOT NULL DEFAULT 0;

-- 2) SyncResult 컬럼을 "순서 그대로" 추가
-- (begin, end, fetched, deduped, duplicated, insertedCategory, insertedItem, updatedCategory, updatedItem, changed)

ALTER TABLE TB_G2B_SYNC_HIS
    ADD COLUMN BEGIN_DT CHAR(8) NOT NULL DEFAULT '' AFTER STS_YN,
    ADD COLUMN END_DT   CHAR(8) NOT NULL DEFAULT '' AFTER BEGIN_DT,
    ADD COLUMN FETCHED  INT NOT NULL DEFAULT 0 AFTER END_DT,
    ADD COLUMN DEDUPED  INT NOT NULL DEFAULT 0 AFTER FETCHED,
    ADD COLUMN DUPLICATED INT NOT NULL DEFAULT 0 AFTER DEDUPED,
    ADD COLUMN INSERTED_CATEGORY INT NOT NULL DEFAULT 0 AFTER DUPLICATED,
    ADD COLUMN INSERTED_ITEM     INT NOT NULL DEFAULT 0 AFTER INSERTED_CATEGORY,
    ADD COLUMN UPDATED_CATEGORY  INT NOT NULL DEFAULT 0 AFTER INSERTED_ITEM,
    ADD COLUMN UPDATED_ITEM      INT NOT NULL DEFAULT 0 AFTER UPDATED_CATEGORY;

-- 3) CHANGED 컬럼 위치를 SyncResult 순서에 맞춰 마지막으로 이동
-- MySQL은 MODIFY로 위치 조정 가능
ALTER TABLE TB_G2B_SYNC_HIS
    MODIFY COLUMN CHANGED BIGINT NOT NULL DEFAULT 0 AFTER UPDATED_ITEM;

-- 인덱스(조회용) - 선택
CREATE INDEX IX_G2B_SYNC_HIS_1 ON TB_G2B_SYNC_HIS (CRE_AT);
CREATE INDEX IX_G2B_SYNC_HIS_2 ON TB_G2B_SYNC_HIS (BEGIN_DT, END_DT);
