ALTER TABLE TB_G2B_SYNC_HIS
    ADD COLUMN UPD_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM' AFTER CRE_BY,
    ADD COLUMN UPD_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER CRE_AT;

CREATE INDEX IX_G2B_SYNC_HIS_UPDAT ON TB_G2B_SYNC_HIS(UPD_AT);