CREATE TABLE TB_G2B_SYNC_HIS (
        SYNC_HIS_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
        STS_YN CHAR(1) NOT NULL, -- 성공여부

        G2B_M_NM_CHG_CNT INT NOT NULL DEFAULT 0,  -- 분류명 변경 건수
        G2B_D_NM_CHG_CNT INT NOT NULL DEFAULT 0, -- 식별명(물품명) 변경 건수
        UPR_CHG_CNT INT NOT NULL DEFAULT 0,   -- 계약단가 변경 건수

        ERR_CD CHAR(3) NULL, -- 실패했다면 어떤 에러인지
        CRE_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
        CRE_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);