CREATE TABLE TB_G2B_STG
(
    `STG_ID`   BIGINT AUTO_INCREMENT PRIMARY KEY,
    `G2B_M_CD` CHAR(8) NOT NULL COMMENT '물품분류코드',
    `G2B_M_NM` VARCHAR(300) NOT NULL COMMENT '물품분류명',
    `G2B_D_CD` CHAR(8) NOT NULL COMMENT '물품식별코드',
    `G2B_D_NM` VARCHAR(300) NOT NULL COMMENT '물품품목명',
    `G2B_UPR`  DECIMAL(20, 0) NOT NULL COMMENT '조달청 기준 계약단가(원)'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE TB_G2B_SYNC_HIS (
    SYNC_HIS_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    STS_YN CHAR(1) NOT NULL, -- 성공여부

    CHG_CNT INT NOT NULL DEFAULT 0,   -- 변경 건수

    ERR_CD CHAR(3) NOT NULL DEFAULT '200',
    CRE_BY VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    CRE_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);