TRUNCATE TABLE TB_USER001M;
TRUNCATE TABLE TB_ORG002M;
TRUNCATE TABLE TB_ORG001M;

ALTER TABLE TB_ORG001M
    MODIFY ORG_CD CHAR(7) NOT NULL COMMENT '조직코드(의미코드)';
ALTER TABLE TB_ORG002M
    MODIFY ORG_CD CHAR(7) NOT NULL COMMENT '조직코드(FK)',
    CHANGE DEPT_TY UP_DEPT_NM VARCHAR(255) NOT NULL COMMENT '상위부서명';
ALTER TABLE TB_USER001M
    MODIFY ORG_CD CHAR(7) NOT NULL COMMENT '조직코드(FK)';

ALTER TABLE TB_ORG002M
    ADD CONSTRAINT FK_TB_ORG002M_ORG
        FOREIGN KEY (ORG_CD)
            REFERENCES TB_ORG001M (ORG_CD)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT;

ALTER TABLE TB_USER001M
    ADD CONSTRAINT FK_TB_USER001M_ORG
        FOREIGN KEY (ORG_CD)
            REFERENCES TB_ORG001M (ORG_CD)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT;