CREATE TABLE TB_G2B_USRFUL (
    G2B_M_CD VARCHAR(20) NOT NULL COMMENT '물품분류번호 (PK)',
    G2B_M_NM VARCHAR(255) NOT NULL COMMENT '품명',
    DRB_YR VARCHAR(20) DEFAULT 0 COMMENT '내용연수 (Year)',
    CRE_BY VARCHAR(100) NOT NULL COMMENT '생성자',
    CRE_AT DATETIME NOT NULL COMMENT '생성일',
    UPD_BY VARCHAR(100) COMMENT '수정자',
    UPD_AT DATETIME COMMENT '수정일',
    PRIMARY KEY (G2B_M_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4