USE usto;

ALTER TABLE `TB_ITEM005M`
    CHANGE COLUMN `DISP_AT` `APLY_AT` DATE NOT NULL COMMENT '처분(등록)일자';

ALTER TABLE `TB_ITEM005M`
    ADD COLUMN `DISP_APPR_AT` DATE NULL COMMENT '처분확정일자' AFTER `APPR_USR_ID`;