-- 모든 작업은 워크벤치에서 하는 걸 추천드립니다.

use usto;
show tables;

-- 0) 로컬 파일 로드 허용 확인/설정
SHOW VARIABLES LIKE 'local_infile'; -- ON이여야합니다.
SET GLOBAL local_infile = 1;

-- 1) RAW 테이블 생성
DROP TABLE IF EXISTS TB_G2B_RAW;
CREATE TABLE TB_G2B_RAW (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  G2B_M_CD char(8),
  G2B_M_NM varchar(300),
  G2B_D_CD char(8),
  G2B_D_NM varchar(300),
  G2B_UPR DECIMAL(20,0),
  G2B_UPR_RAW VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2) 적재
LOAD DATA LOCAL INFILE 'D:/g2b_list.csv' -- 이거는 예영님에게 맞게 수정하셔야합니다
INTO TABLE TB_G2B_RAW
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(G2B_M_CD, G2B_M_NM, G2B_D_CD, G2B_D_NM, @upr_raw)
SET
  G2B_UPR_RAW = @upr_raw,
  G2B_UPR=
    CASE
      WHEN @upr_raw IS NULL OR TRIM(@upr_raw) = '' THEN NULL
      WHEN REPLACE(TRIM(@upr_raw), ',', '') REGEXP '^[0-9]+$'
        THEN CAST(REPLACE(TRIM(@upr_raw), ',', '') AS DECIMAL(20,0))
      ELSE NULL
    END;

-- 3) 검증
SELECT COUNT(*) AS row_count 
FROM TB_G2B_RAW;

SELECT COUNT(DISTINCT G2B_D_CD)
FROM TB_G2B_RAW;

SELECT *
FROM TB_G2B_RAW
WHERE G2B_D_CD = '24612653';

SELECT * 
FROM TB_G2B_RAW 
LIMIT 100;

-- TB_G2B001M

DROP TABLE IF EXISTS TB_G2B001M;
CREATE TABLE TB_G2B001M (
  G2B_M_CD CHAR(8) PRIMARY KEY COMMENT '물품분류코드',
  G2B_M_NM VARCHAR(300) NOT NULL COMMENT '물품분류명',
  CRE_BY VARCHAR(30) NOT NULL COMMENT '레코드 생성 주체',
  CRE_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '레코드 생성 시점',
  UPD_BY VARCHAR(30) NULL COMMENT '마지막 레코드 업데이트 주체',
  UPD_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '마지막 레코드 업데이트 시점'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO TB_G2B001M (
  G2B_M_CD,
  G2B_M_NM,
  CRE_BY,
  CRE_AT
)
SELECT DISTINCT
  G2B_M_CD,
  G2B_M_NM,
  'SYSTEM',
  NOW()
FROM TB_G2B_RAW
WHERE G2B_M_CD IS NOT NULL;

SELECT COUNT(*) AS row_count FROM TB_G2B001M;
SELECT * FROM TB_G2B001M LIMIT 100;

-- TB_G2B001D

DROP TABLE IF EXISTS TB_G2B001D;
CREATE TABLE TB_G2B001D (
  G2B_D_CD CHAR(8) NOT NULL PRIMARY KEY COMMENT '물품식별코드',
  G2B_M_CD CHAR(8) NOT NULL COMMENT '물품분류코드 FK TB_G2B001M',
  G2B_D_NM VARCHAR(300) NOT NULL COMMENT '물품품목명',
  G2B_UPR DECIMAL(20,0) NOT NULL COMMENT '조달청 기준 계약단가(원)',
  CRE_BY VARCHAR(30) NOT NULL COMMENT '레코드 생성 주체(USER_ID 또는 SYSTEM)',
  CRE_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '레코드 생성 시점',
  UPD_BY VARCHAR(30) NULL COMMENT '조달청 정보 마지막 업데이트 주체',
  UPD_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '조달청 정보 마지막 업데이트 시각',

  KEY IDX_TB_G2B001D_M (G2B_M_CD),

  CONSTRAINT FK_TB_G2B001D_M
    FOREIGN KEY (G2B_M_CD)
    REFERENCES TB_G2B001M (G2B_M_CD)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_RAW_DCD_UPR ON TB_G2B_RAW (G2B_D_CD, G2B_UPR); -- 오래 걸림

INSERT INTO TB_G2B001D (
  G2B_D_CD,
  G2B_M_CD,
  G2B_D_NM,
  G2B_UPR,
  CRE_BY,
  CRE_AT
)
SELECT
  G2B_D_CD,
  ANY_VALUE(G2B_M_CD),
  ANY_VALUE(G2B_D_NM),
  MAX(G2B_UPR),
  'SYSTEM',
  NOW()
FROM TB_G2B_RAW
WHERE G2B_D_CD IS NOT NULL
  AND G2B_M_CD IS NOT NULL
  AND G2B_UPR IS NOT NULL
GROUP BY G2B_D_CD; -- 매우 오래걸립니다.(렉 아니에요)

SELECT COUNT(*) AS row_count FROM TB_G2B001D;
SELECT * FROM TB_G2B001D LIMIT 100;

-- 여기까지 하시면 조달청 데이터는 전부 다 가져온겁니다.
